# Generated by Django 5.1.6 on 2025-08-29 11:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('user_id', models.CharField(db_index=True, max_length=200)),
                ('price_per_unit', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrices',
            fields=[
                ('arrival_date', models.DateField()),
                ('market', models.CharField(max_length=100)),
                ('commodity', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('modal_price', models.FloatField()),
                ('source', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'market_prices',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
    ]
