# syncapp/commodity_map.py

def normalize_key(key: str) -> str:
    if not key:
        return ""
    key = key.lower().strip()
    key = key.replace("(", "").replace(")", "")
    key = key.replace("-", " ").replace("/", " ")
    key = key.replace("__", "_")
    return key

# Original mapping (cleaned and deduplicated)
COMMODITY_MAP = {
    "Onion": "कांदा",
    "Tomato": "टोमॅटो",
    "Potato": "बटाटा",

    # "Amla": "आवळा",
    # "Areca Nut": "सुपारी",
    # "Arhar Dal(Tur Dal)": "तूर डाळ",
    # "Arhar (Tur/Red Gram)(Whole)": "तूर डाळ",
    # "Ash Gourd": "दुधी भोपळा",
    # "Banana": "केळी",
    # "Banana - Green": "केळी (हिरवी)",
    # "Beet": "बीट",
    # "Beetroot": "रताळी",
    # "Bengal Gram Dal (Chana Dal)": "चवळी (शेंगा)",
    # "Bengal Gram(Gram)(Whole)": "हरभरा",
    # "Bitter Gourd": "कारली",
    # "Black Gram Dal (Urd Dal)": "उडीद",
    # "Black Gram (Urd Beans)(Whole)": "उडद",
    # "Bottle Gourd": "कोहळा",
    # "Bottle Gourd (Shepu)": "शेपू",
    # "Brinjal": "वांगी",
    # "Cabbage": "कोबी",
    # "Carrot": "गाजर",
    # "Cashew": "काजू",
    # "Cauliflower": "फ्लॉवर",
    # "Chawli Beans": "चवळी (शेंगा)",
    # "Chili Red": "लाल मिरची",
    # "Chilly Capsicum": "शिमला मिरची",
    # "Cloves": "मिरे",
    # "Colocasia": "घेवडा",
    # "Coriander": "धने",
    # "Coriander Leaves": "कोथिंबिर",
    # "Coriander(Leaves)": "धनेची पाने",
    # "Coriander Seeds": "बडिशेप",
    # "Coconut": "नारळ",
    # "Cucumber": "काकडी",
    # "Cucumbar(Kheera)": "काकडी",
    # "Dolichos Bean": "दोडका (शिराळी)",
    # "Dry Ginger": "आले",
    # "Elephant Foot Yam": "सुरण",
    # "Elephant Yam (Suran)": "सुरण",
    # "Fenugreek Leaves": "मेथी भाजी",
    # "Fenugreek Seeds": "मेथी बी",
    # "Fars Beej": "फरस बी",
    # "Garlic": "लसूण (सुका)",
    # "Garlic (Dry)": "लसूण (सुका)",
    # "Ginger(Green)": "आले (सुंठ)",
    # "Ginger(Dry)": "आले (सुकलेले)",
    # "Green Chilli": "मिरची (हिरवी)",
    # "Green Chilli (Hirvi)": "मिरची (हिरवी)",
    # "Green Gram (Moong)(Whole)": "गवार",
    # "Green Gram Dal (Moong Dal)": "मूग डाळ",
    # "Green gram (moong)(whole)": "मूग",
    # "Guava": "पेरू",
    # "Gur(Jaggery)": "गूळ",
    # "Jaggery": "गुळ",
    # "Karadi (Bhaji)": "करडई (भाजी)",
    # "Lemon": "लिंबू",
    # "Lime": "लिंबू",
    # "Masur Dal": "मसूर डाळ",
    # "Lentil (Masur)(Whole)": "मसूर",
    # "Mint": "पुदिना",
    # "Mint(Pudina)": "पुदिना",
    # "Mosambi": "मोसंबी",
    # "Mustard": "मोहरी",
    # "Okra": "भेंडी",
    # "Bhindi(Ladies Finger)": "भेंडी",
    # "Tamarind Fruit": "चिंच",
    # "Onion": "कांदा",
    # "Onion Green": "कांदा पात",
    # "Parwar": "परवर",
    # "Peanut (Oil)": "भुईमुग शेंग (ओली)",
    # "Potato": "बटाटा",
    # "Pomegranate": "डाळींब",
    # "Pumpkin": "भोपळा",
    # "Sweet Pumpkin": "गोड भोपळा",
    # "Radish": "मुळा",
    # "Raw Banana": "केळी (कच्ची)",
    # "Raw Mango": "कैरी",
    # "Rice Flour": "तांदुळजा",
    # "Rice": "तांदूळ",
    # "Spinach": "पालक",
    # "Sugar": "साखर",
    # "Sweet Potato": "शकरकंद",
    # "Tamarind": "चिंच",
    # "Tomato": "टोमॅटो",
    # "Toondli": "तोंडली",
    # "Turmeric": "हळद/ हळकुंड",
    # "Walnut": "वालवड",
    # "Wheat": "गहू",
    # "Chikoos(Sapota)": "चीकू",
    # "Marigold(Calcutta)": "केंवळ",
    # "Ragi (finger millet)": "रागी",
    # "Jowar(Sorghum)": "ज्वारी",
    # "Paddy(Dhan)(Common)": "तांदूळ",
    # "Sesamum(Sesame,Gingelly,Til)": "तीळ",
    # "Almond(Badam)": "बदाम",
    # "Bajra(Pearl Millet/Cumbu)": "बाजरी",
    # "Peas Wet": "फोडणी वाटाणे",
    # "Ridgeguard(Tori)": "टोऱी",
    # "Cummin Seed(Jeera)": "जिरे",
    # "Ground Nut Seed": "शेंगदाण्याची बियाणे",
    # "Pointed gourd (Parval)": "परवल",
    # "Little gourd (Kundru)": "कुंदरू",
    # "Snakeguard": "शेवगा",
    # "Papaya": "पपई",
    # "Orange": "संत्रा",
    # "Apple": "सफरचंद",
    # "Drumstick": "शेवगा/सहजन",
    # "Guar": "ग्वार",
    # "Seetapal": "सीताफळ",
    # "Soyabean": "सोयाबीन",
    # "Water melon": "कलिंगड"
    
}

# ✅ One normalized dictionary for reliable lookup
COMMODITY_MAP_LOCAL = {normalize_key(k): v for k, v in COMMODITY_MAP.items()}
